import type { Metadata } from "next";
import "../globals.css";
import Header from "../_components/Header";
import Footer from "../_components/Footer";
import { FilterProvider } from "../../contexts/FilterContext"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <FilterProvider>
          <Header />
          <main className="content-wrap">{children}</main>
          <Footer />
        </FilterProvider>
      </body>
    </html>
  );
}
